name: Deploy

on: 
  push:
    branches:
    - master

jobs:
  deploy:
    name: Deploy to Deta Space
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy
      uses: neobrains/space-deployment-github-action@v0.5
      with:
        access_token: ${{ secrets.SPACE_ACCESS_TOKEN }}
        project_id: ${{ secrets.SPACE_ID }}
        space_push: true
